### ISSUE TITLE
One Question of AC6 paramdexName 

### ISSUE THREAD

**Issue by Nipaoni** [ividyon/WitchyBND#12]
Thanks about make tool. I created a new part using your tools. 
However, the created parts have an ID instead of a name in-game. When I checked, paramdexName disappeared as the file went through the conversion process. 
 I think there is no paramdexName corresponding to the new ID. Can you tell me where paramdexName is referenced during the conversion process?

**Comment by ividyon** [comment]
Names are not declared in parameters. They're declared in FMG files in the `msg` folder.

Names in the params are only for development purposes.

If you want to add a development name, add it as `name` instead of `paramdexName`. `paramdexName` is purely a helper entry to help identify rows at a glance, and is not converted back into the param.

If you want names to appear ingame, PARAM is not the place; add new entries in FMG files.

**Comment by Nipaoni** [comment]
Thanks to you!! made mod. 
https://www.nexusmods.com/armoredcore6firesofrubicon/mods/50?tab=description
