### ISSUE TITLE
Cannot serialize param files inside AC6 graphicsconfig.param.dcx

### ISSUE THREAD

**Issue by LibretroAdmin** [ividyon/WitchyBND#18]
For instance, here is what happens when trying to turn GraphicsConfig_LightingQuality_win64.param into XML :

> C:\Apps\WitchyBND-Sekiro\GraphicsConfig_LightingQuality_win64.param: Param type GRAPHICS_CONFIG_CS_LIGHTING_QUALITY_DETAIL not found in AC6 paramdefs.

What happens with GraphicsConfig_VolumetricEffectQuality_win64.param: 

> C:\Apps\WitchyBND-Sekiro\GraphicsConfig_VolumetricEffectQuality_win64.param: Param type GRAPHICS_CONFIG_CS_VOLUMETRIC_EFFECT_QUALITY_DETAIL not found in AC6 paramdefs.

This happens with the latest AC6 installed. I am selecting 'Armored Core VI' from the dropdown list and then inputting the specified regulation version (10210005).

**Comment by ividyon** [comment]
Yeah, paramdefs were never made for this. They're usually only maintained by the community for the "game" params, which are in the regulation.bin in newer titles. People don't seem to particularly care about these other ones.

You can try copying the paramdefs prefixed `Gconfig_` from the `Assets\Paramdex\ER\Defs` folder into the AC6 one, and changing the `ParamType` to match the one this error message is asking from you (the ER ones only say `CS_LIGHTNING_QUALITY_DETAIL` instead of `GRAPHICS_CONFIG_CS_LIGHTNING_QUALITY_DETAIL`, for example), and see if that is already enough to parse these files. Since it's a different game, it might not be, especially since raytracing got introduced.

There's probably nothing too exciting in there, though.

**Comment by LibretroAdmin** [comment]
Thanks, it seems to have worked for ReflectionQuality. I'll try it for the other ones as well.

If this all pans out, would you like a PR for this?

**Comment by ividyon** [comment]
It's probably better to PR the paramdef updates to DSMapStudio, since
that's where the Paramdex is maintained, and I just source it from there.
